'''
language: python
python:
  - "3.8"
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coverage
script:
  - coverage run -m unittest discover
after_sucess:
  - bash <(curl -s https://codecov.io/bash)
''''