name: Python Develop Workflow
on:
  push:
    branches:
      - 'develop'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pip3 install codecov
          pip3 install coverage
          coverage run -m unittest discover
          echo $(pwd)
          echo $(ls)
      - name: Upload coverage to Codecov
        run:
          bash <(curl -s https://codecov.io/bash)